import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Client, { urlFor } from "Client";
import { useState } from "react";
import { Variables } from "Types";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }: any) {
  console.log(data);
  const [react, setReact] = useState(data);
  return (
    <>
      <Head>
        <title>FDOCS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="max-md:ml-0  ml-56 pr-4 pt-20 pb-8 px-4 ">
          {react?.map((value: Variables) => (
            <div className="flex flex-col gap-6" key={value?.id}>
              <h4 className="text-[#0EA5E9] text-xl font-semibold ">
                {value.name}
              </h4>
              <p className="text-justify text-sm ">{value?.content}</p>
              <p className="text-justify text-sm ">{value?.ending}</p>
              <img
                className="w-full h-[200px] object-cover rounded-lg"
                src={urlFor(value?.image.asset._ref).url()}
                alt="reactlogo"
              />
              <div className="text-justify text-sm flex flex-col gap-4 ">
                <h2 className="text-xl font-bold">
                  create your first react application with Production-grade
                  React frameworks{" "}
                </h2>
                <p>{value?.guide}</p>
                <span className="bg-[#333] text-white h-10 px-4 rounded-lg flex items-center">
                  {value?.npm}
                </span>
              </div>
              <div className="text-justify text-sm flex flex-col gap-4 ">
                <h2 className="text-xl font-bold">
                  {value?.npm_additional_package}{" "}
                </h2>
                <p>{value?.yarn_additional_package}</p>
                <span className="bg-[#333]  text-white h-16 py-2 px-4 rounded-lg flex gap-2 flex-col items-start">
                <span>npm create vite@latest   your-app-name </span> 
                <span>  yarn create vite  your-app-name </span>
                </span>
              </div>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps(context: any) {
  const query = `*[_type == "About" && name=="React.js"]`;
  const data = await Client.fetch(query);

  return {
    props: {
      data,
    },
  };
}
