import React,{useState} from 'react'
import Head from 'next/head'
import Client from 'Client'
import { Variables } from 'Types'
import { urlFor } from 'Client'
const UseContext = ({usecontext}:any) => {
    const [react,setReact]=useState(usecontext)
  return (
    
    <>
    <Head>
        <title>useEffect</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="  max-md:ml-0  ml-56 px-4  pr-4 pt-20 pb-8">
        {react?.map((value: Variables) => (
          <div className="flex flex-col gap-4" key={value?.id}>
            <h4 className=" text-[#0EA5E9] text-xl font-semibold ">
              {value.name}
            </h4>
            <p className="text-justify text-sm ">{value?.content}</p>
            <p className="text-justify text-sm ">{value?.ending}</p>

            <img
              className="w-full  h-[360px] object-cover rounded-lg"
              alt="code "
              src={urlFor(value?.image.asset._ref).url()}
            />
           
            <div className="text-justify text-sm flex flex-col gap-4 ">
              <p>{value?.guide}</p>
            </div>
            <img alt="code example" className="w-full  h-[320px] object-cover rounded-lg" src={urlFor(value?.additional_image.asset._ref).url()}/>
          </div>
        ))}
      </div>
    </>
  )
}

export default UseContext

export async function getServerSideProps(context: any) {
    const query = `*[_type == "About" && name=="useContext"]`;
    const usecontext = await Client.fetch(query);
  
    return {
      props: {
        usecontext,
      },
    };
  }